# Generated by Django 3.2.4 on 2021-10-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211022_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
